version: "3"
services:
  php:
    container_name: bnb-bank-php
    build:
      context: ./docker/php
    networks:
      - bnb-bank
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis

  nginx:
    container_name: bnb-bank-nginx
    build: ./docker/nginx
    networks:
      - bnb-bank
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
    depends_on:
      - php
  
  mysql:
    container_name: bnb-bank-mysql
    image: mysql:8
    networks:
      - bnb-bank
    ports:
      - "3206:3306"
    volumes:
      - ./docker/mysql/dbdata:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: bnb-bank
      MYSQL_ROOT_PASSWORD: root
  
  redis:
    container_name: bnb-bank-redis
    image: redis:alpine
    networks:
      - bnb-bank
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/dbdata:/data

networks:
  bnb-bank:
    driver: bridge

volumes:
  node_modules: